### ISSUE TITLE
on  ArtifactoryClient.create exception thrown 

### ISSUE THREAD

**Issue by AdityaAgg** [JFrogDev/artifactory-client-java#85]
I'm getting the following error when I try to instantiate the Artifactory client.

This seems similar to Issues #22 and #15 

`ArtifactoryClient artifactory = ArtifactoryClient.create(resolverServerUrl, resolverUsername, resolverPassword);`

`
groovy.lang.MissingMethodException: No signature of method: com.fasterxml.jackson.databind.ObjectMapper.addMixIn() is applicable for argument types: (java.lang.Class, java.lang.Class) values: [interface org.jfrog.artifactory.client.model.Repository, ...]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at org.jfrog.artifactory.client.impl.ArtifactoryImpl.<init>(ArtifactoryImpl.groovy:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
	at org.jfrog.artifactory.client.ArtifactoryClient.create(ArtifactoryClient.groovy:87)
	at org.jfrog.artifactory.client.ArtifactoryClient.create(ArtifactoryClient.groovy)
	at com.jenkins.plugins.servicenow.artifactory.ArtifactoryService.<init>(ArtifactoryService.java:36)
	at com.ge.integration.jenkins.notification.Phase.initialize(Phase.java:152)
	at com.ge.integration.jenkins.notification.Phase.perform(Phase.java:210)
	at com.ge.integration.jenkins.notification.Phase.handle(Phase.java:114)
	at com.ge.integration.jenkins.notification.JobListener.onFinalized(JobListener.java:52)
	at hudson.model.listeners.RunListener.fireFinalized(RunListener.java:230)
	at hudson.model.Run.onEndBuilding(Run.java:1890)
	at hudson.model.Run.execute(Run.java:1809)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)`

**Comment by AdityaAgg** [comment]
Update: 
With regards to versioning
I'm using the latest version of this library.
*Jenkins 1.621 
Artifactory 2.3.0*

The environment I am using this for requires these versions.

I have tried on Java 1.8.02 and Java 1.7.79

**Comment by romangurevitch** [comment]
Thanks for reporting this @AdityaAgg, 
We will check and fix the issue.
It would help us if you could provide us a sample project that reproduces the issue.

**Comment by AdityaAgg** [comment]
Solved, going to close the issue.

I was using the wrong version of the Jackson Library. JFrog's client library imports and requires Jackson 2.4.6; however, I had imported Jackson 2.1.1 in a dependency that I imported before hand.

My build tool (Maven) read it as a conflict and used 2.1.1 omitting 2.4.6, causing the error described above.
